### ISSUE TITLE
refactor(deployment): Railway migrations

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/random-travelers#115]
## AsIs
No production deployment exists now, because of GKE cluster had been removed for cost perspectives.

## ToDo
- [x] create apps from container image on Railway
- [x] deploy dedicated MySQL database on Railway for the app
- [x] add `railway.toml` to repository ([docs](https://docs.railway.com/guides/config-as-code))

## (Optional) Acceptance Criteria
Initial access to app on Railway.

**Comment by hwakabh** [comment]
Now we have implemented all the tasks to application/pipelines with Railway, will close the issue now.
