### ISSUE TITLE
build: assign custom domain with Ingress

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/random-travelers#94]
## AsIs
With the changes for #63, as we had confirmed that we can access to FastAPI application in production environment with GKE cluster, still we have to replace serviceType from `LoadBalancer` to `ClusterIP` with Ingress resource.

As noted in https://github.com/hwakabh/random-travelers/pull/65#issuecomment-1899841267, we can reach IP address of serviceType `LoadBalancer` from client, but this is not a static one and not being name-resolved.

## ToDo
- [x] add Ingress resource to access application with static IP
- [x] add cert-manager for TLS connection with Ingress
- [x] add configurations to domain registrar for pointing from custom domain to static IP

## (Optional) Acceptance Criteria
- confirm TLS access to application with custom domain

**Comment by hwakabh** [comment]
<img width="1678" alt="Screenshot 2024-03-16 at 0 23 40" src="https://github.com/hwakabh/random-travelers/assets/25563897/77268c2a-b85b-43dc-873a-c7d5ebe583aa">
